version: '3'
services:
  mongoDb:
    image: mongo
    ports: 
      - 27017:27017
    volumes:
      - mongoData:/data/db 
      - mongoConfig:/data/configdb
  generic-api:    
    ports: 
     - 80:3000
    build: 
      context: .
      dockerfile: .

volumes:
    mongoData:
    mongoConfig: