version: '3.4'

services:
  mongoDb:
    image: mongo
    ports: 
      - 27017:27017
    volumes:
      - mongoData:/data/db 
      - mongoConfig:/data/configdb  
  generic-api:
    image: generic-api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      REPOS: "trains"
    ports:
      - 80:3000
volumes:
    mongoData:
    mongoConfig: